#!/bin/sh

Help()
{
   # Display Help
   echo "Kankyou: compare two environments."
   echo
   echo "Syntax: kankyou [OPTIONS] BACK REAL"
   echo "options:"
   echo "h     Print this Help."
   echo "n     Compare only existing, but different files."
   echo "m     See only missing files."
   echo "V     Print software version and exit."
   echo
}

KANKYOU="$(basename "$0")"

if [ $# -gt 2 ]; then
    echo 1>&2 "$KANKYOU: too many arguments. I only compare 2."
    exit 2
elif [ $# -lt 1 ]; then
    echo 1>&2 "$KANKYOU: not enough arguments. You need to specify at least the source path."
    echo 1>&2 "$KANKYOU: maybe you wanted to say 'kankyou .'?"
    exit 2
elif [ $# = 1 ]; then
    REAL="$HOME"
else
    REAL="$(realpath $2)"
fi

BACK="$(realpath $1)"
FILES=$(diff -qr "$BACK" "$REAL" | grep -v '^Only in' | awk '{print $2} {print $4}')

if [ -z "$FILES" ]; then
    echo 1>&2 "$KANKYOU: no files sharing the same name differ."
    echo 1>&2 "$KANKYOU: there are two possibilities:"
    echo 1>&2 "$KANKYOU: 1. everything is up to date."
    echo 1>&2 "$KANKYOU: 2. you have misspecified the directories."
    exit 2
elif [ "$REAL" = "$HOME" ]; then
    TARGET=$(echo $FILES | xargs -n 2 | awk '{print $2}' | xargs -n 1 realpath --relative-to=$HOME | fzf)
else
    TARGET=$(echo $FILES | xargs -n 2 | awk '{print $2}' | xargs -n 1 realpath | fzf)
fi

echo $FILES | xargs -n 2 | grep $TARGET | xargs git diff
