#!/bin/sh

weekday="$(date '+%a')"
clock="$(date '+%b %d / %R')"

if [ "$weekday" = "Mon" ]
then
  icon="月"
elif [ "$weekday" = "Tue" ]
then
  icon="火"
elif [ "$weekday" = "Wed" ]
then
  icon="水"
elif [ "$weekday" = "Thu" ]
then
  icon="木"
elif [ "$weekday" = "Fri" ]
then
  icon="金"
elif [ "$weekday" = "Sat" ]
then
  icon="土"
else
  icon="日"
fi

echo "$icon / $clock "
