#!/bin/sh

# merge Xresources
xrdb "$HOME/.config/x11/Xresources"

# keyboard repeat rate
xset r rate 300 60

# stop screen blanking
xset s off
xset -dpms
xset s noblank

# clipboard managers
parcellite -n &
clipmenud &

# transparency, wallpaper, themes
xcompmgr &
"$HOME/.config/dynconf/aesthetics" "guess"

# apply Xmodmap (Right Ctrl -> MODKEY)
#xmodmap ~/.Xmodmap

# input method for dead keys / Japanese
export XMODIFIERS=@im=local

# audio
#pipewire &

# notification & status
dunst &
dwmblocks &

# start window manager
exec dbus-launch --sh-syntax --exit-with-session dwm
