#!/bin/sh
channel=$(amixer | grep "Left: Playback" | awk -F "[" '{print $3}' | awk -F "]" '{print $1}')
vol="$(amixer sget Master | awk -F"[][]" '/Left:/ { print $2 }' | awk -F "%" '{print $1}')"

[ $channel = "off" ] && echo "   $vol" && exit

if [ "$vol" -gt "50" ]
then
	icon=" "
else
	icon=" "
fi

echo "  $icon$vol"
