[ids]
*

[main]
# Caps_Lock produces ESC when tapped
# holding Caps_Lock enables the "emacs_ctrl_layer" layer
capslock = overload(control, esc)
# holding Alt enables the "emacs_alt_layer"
#leftalt = layer(emacs_alt_layer)

# Copilot key = AltGr (I sometimes miss AltGr because they are side to side)
leftshift+leftmeta+f23 = layer(altgr)

# Tapping both shift keys will activate capslock.
shift = layer(my_shift_layer)

[my_shift_layer:S]
leftshift = capslock
rightshift = capslock

#[emacs_ctrl_layer:C]
## Basic Emacs (C-b,C-f,C-n,C-p) movement
#b = left
#f = right
#p = up
#n = down
## C-a = Home
#a = home
## C-e = End
#e = end

#[emacs_alt_layer:A]
## Jump between words with Alt-b / Alt-f
#b = C-left
#f = C-right
