#!/bin/bash
if [ $(pgrep "mpd") ]; then
  mpc -q next
elif [ $(pgrep "clementine" | sed 1q) ]; then
  playerctl --player=clementine next
elif [ $(pgrep "spotify" | sed 1q) ]; then
  playerctl --player=spotify next
fi
