#!/bin/sh

# sudo not required for some system commands
for command in mount umount sv su poweroff reboot zzz ; do
	alias $command="sudo $command"
done; unset command

# colors for commands
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    la='ls -A' \
    ll='ls -lA' \
    grep='grep --color=auto' \
    egrep='grep -E --color=auto' \
    fgrep='grep -F --color=auto' \
    diff='diff --color=auto' \
    ip='ip --color=auto' \
    ccat="highlight --out-format=ansi"

# abbreviations
alias \
    sudo="sudo " \
    py="python" \
    v="vim" \
    vi="vim" \
    nv="nvim" \
    rg="ranger" \
    tmux="tmux -2" \
    m="make" \
    mc="make clean" \
    km="killall mpd" \
    nf="neofetch | lolcat" \
    net="sudo netrestart" \
    xbi="sudo xbps-install" \
    xbq="xbps-query" \
    xbr="sudo xbps-remove" \
    xbdb="sudo xbps-pkgdb" \
    pg="ps aux | grep" \
    fd="source fzfcd" \
    chx="chmod +x" \
    ren="perl-rename" \
    xsel="xsel --logfile $HOME/.cache/xsel.log"
