#!/bin/bash

hour=$(date '+%H')
dyncfg="$HOME/.config/dynamic-config"
wplight=wallpaper-light.png
wpdark=wallpaper-dark.jpg
#wplight=$(ls $dyncfg | grep wallpaper-light)
#wpdark=$(ls $dyncfg | grep wallpaper-dark)

if [[ 10#$hour -ge 7 && 10#$hour -le 17 ]]; then
	feh --no-fehbg --bg-scale $dyncfg/$wplight
	cp $dyncfg/gtkrc-light /etc/gtk-2.0/gtkrc
	cp $dyncfg/settings.ini-light /etc/gtk-3.0/settings.ini
	cp $dyncfg/zathurarc-light $HOME/.config/zathura/zathurarc
else
	feh --no-fehbg --bg-scale $dyncfg/$wpdark
	cp $dyncfg/gtkrc-dark /etc/gtk-2.0/gtkrc
	cp $dyncfg/settings.ini-dark /etc/gtk-3.0/settings.ini
	cp $dyncfg/zathurarc-dark $HOME/.config/zathura/zathurarc
fi
