#!/bin/sh

bat="$(acpi | awk -F', ' '{print $2}' | awk -F'%' '{print $1}')"
status="$(acpi | awk -F',' '{print $1}' | awk '{print $3}')"

if [ "$bat" -lt 15 ] && [ "$status" = "Discharging" ]
then
  notify-send -u critical "BATERIA ACABANDO!"
elif [ "$bat" -lt 35 ] && [ "$status" = "Discharging" ]
then
  notify-send "Bateria baixa!"
fi
